# Run template for latest fiducial grid-based 21cmfast runs

[CosmoParams]

[UserParams]
HII_DIM = 200
DIM = 300
BOX_LEN = 300
HMF = 'ST'
SAMPLER_MIN_MASS = 1e10
AVG_BELOW_SAMPLER = true

[AstroParams]
R_BUBBLE_MAX = 50.0

[FlagOptions]
USE_HALO_FIELD = true
HALO_STOCHASTICITY = true
USE_EXP_FILTER = true
CELL_RECOMB = true
USE_MINI_HALOS = false
USE_TS_FLUCT = true
INHOMO_RECO = true
