# Run template for reproducing Park19 fiducial results

[CosmoParams]

[UserParams]
USE_RELATIVE_VELOCITIES = false
HII_DIM = 200
DIM = 300
BOX_LEN = 300
HMF = 'ST'
USE_INTERPOLATION_TABLES = true
MINIMIZE_MEMORY = true
SAMPLER_MIN_MASS = 1e10
AVG_BELOW_SAMPLER = true

[AstroParams]
F_STAR10 = -1.3
F_ESC10 = -1.0
ALPHA_STAR = 0.5
ALPHA_ESC = 0.5
UPPER_STELLAR_TURNOVER_INDEX = -0.61
M_TURN = 8.7
UPPER_STELLAR_TURNOVER_MASS = 11.447
t_STAR = 0.5
L_X = 40.5
NU_X_THRESH = 500
R_BUBBLE_MAX = 50.0
SIGMA_STAR = 0.3
SIGMA_SFR_INDEX = -0.12
SIGMA_SFR_LIM = 0.19
CORR_STAR = 0.5

[FlagOptions]
USE_HALO_FIELD = true
HALO_STOCHASTICITY = true
USE_EXP_FILTER = false
CELL_RECOMB = false
USE_MINI_HALOS = false
USE_CMB_HEATING = false
USE_LYA_HEATING = false
USE_TS_FLUCT = false
INHOMO_RECO = false
USE_UPPER_STELLAR_TURNOVER = true