# Template for reproducing Gagnon-Hartman et al. (2025)

[CosmoParams]

[SimulationOptions]
HII_DIM = 200
DIM = 600
BOX_LEN = 300
HMF = 'ST'
N_THREADS = 4
SAMPLER_MIN_MASS = 5e8
AVG_BELOW_SAMPLER = true
PERTURB_ON_HIGH_RES = true

[AstroParams]
R_BUBBLE_MAX = 50.0

[AstroOptions]
USE_HALO_FIELD = true
HALO_STOCHASTICITY = true
USE_EXP_FILTER = true
CELL_RECOMB = true
USE_MINI_HALOS = false
USE_TS_FLUCT = true
INHOMO_RECO = true

